// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // `prisma generate` only reads the schema shape, not a live connection,
    // so this fallback keeps builds working even before DATABASE_URL is set
    // in the deployment environment (e.g. Vercel, before Postgres is wired up).
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
